### ISSUE TITLE
Navigation entry not visible

### ISSUE THREAD

**Issue by almare** [shopware/swag-docs-bundle-example#10]
I tried to install the plugin, but I don't see the navigation entry. 

Info: I used a custom docker setup, maybe do I miss something for example extra command calls to rebuild the administration backend. 
Any help is appreciated

**Comment by mitelg** [comment]
hey @almare 
if you use the development template, you could try to run `./psh.phar administration:build` while the plugin is installed and activated. this will rebuild the admin JS files.

**Comment by almare** [comment]
@mitelg thank you for reply

I tried this already after removing the composer require entries, but still no luck. I received one deprecation warning.

```
	(node:639) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
	parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

The result looks good, but I still see no menu entry. Maybe I am wrong my assumption is that the menu item should appear in the left sidebar, right?

**Comment by almare** [comment]
I checkout the v6.0+ea version. Here the menu item appears. It looks like it has to do with the different versions. Maybe this help.

**Comment by mitelg** [comment]
I also get this deprecation message. Should not affect the result. 
but the plugin is used in the build command? you can check that, as there is an output of which packages are used for the build

**Comment by mitelg** [comment]
closed due to inactivity
