### ISSUE TITLE
Product extension not loaded

### ISSUE THREAD

**Issue by dahormez** [shopware/swag-docs-bundle-example#11]
Hi,

The Admin is working fine, but the product.extension in storefront is not filled. Tried to fix this with another association path but its not working. In the first releases of sw/platform it was working, i guess.

Best regards,
Daniel

**Comment by mitelg** [comment]
Hey @dahormez 
where exactly is the extension not filled? where do you try to read it out?

**Comment by keulinho** [comment]
I've just verified that it works with the master version of platform.

Closing for now, please reopen if you still experience problems.

**Comment by phanhongphucit** [comment]
hi @mitelg @keulinho, this issue happens again in the current version of platform.
