### ISSUE TITLE
Uninstall confirmation not showing

### ISSUE THREAD

**Issue by azamalvi** [shopware/swag-docs-bundle-example#13]
I have created a plugin also used this one. Issue is that when I uninstall it must asked to keep the data or delete it, but it simply uninstall and data is not completely removing.

**Comment by mitelg** [comment]
hey @azamalvi 
It seems that this is not yet implemented in the plugin manager module. could you please open a ticket for that here -> https://issues.shopware.com/ ? thanks in advance

**Comment by mitelg** [comment]
hey @azamalvi 
I created an issue for that: https://issues.shopware.com/issues/NEXT-4521 
you can follow the state there

**Comment by azamalvi** [comment]
> hey @azamalvi
> I created an issue for that: https://issues.shopware.com/issues/NEXT-4521
> you can follow the state there

Thanks @mitelg 
By the way I have also created the ticket.

**Comment by mitelg** [comment]
@azamalvi can you link the ticket you created? so I can close the duplicate :wink:
