### ISSUE TITLE
Bundle dont work - database migration missing?

### ISSUE THREAD

**Issue by abssimon** [shopware/swag-docs-bundle-example#16]
Hello,

I use a current docker development version.
I have downloaded the example bundle, ran "./psh.phar administration:build", cleared the cache
and activated the plugin in the admin area. Bundle is visible, but I was not able to assign any products.

Some API calls results in 500er. 

![Bildschirmfoto von 2019-08-14 15-19-34](https://user-images.githubusercontent.com/36915457/63025152-e22e9e80-bea8-11e9-93b8-2c0636df8375.png)

Adminer tells me, there is no "swag_bundle" table or other...
Regarding plugin installation, I can't find any additional informations in the docs.
Are there additional steps needed?

Thank you & Best Regards
Simon

**Comment by mitelg** [comment]
hey @AskanSimon 
If the tables are not created properly, I would try to re-install the plugin. Of course the plugin will not work correctly, if the tables are missing :wink:

**Comment by abssimon** [comment]
Thanks ... ;) this solves the problem ...

bin/console plugin:uninstall BundleExample
bin/console plugin:install --activate --clearCache BundleExample
