### ISSUE TITLE
add-product-detail-extension branch not working

### ISSUE THREAD

**Issue by almare** [shopware/swag-docs-bundle-example#18]
I tried to implement the product extension branch. I found out that some things not working. For example the labels and their translation are not working. 
Additionally I don't get the associated bundles. It would be helpful to get a working solution. Thank you

**Comment by King-of-Babylon** [comment]
Hi almare,
which Shopware 6 version do you use? EA1.1 or the current master from github?

**Comment by almare** [comment]
I use EA1.1. Should I switch to master for further development?

**Comment by keulinho** [comment]
I've rebased the add-product-detail-extension branch and fixed compatibility issues ans then merged the branch.
The current master of this plugin should be compatible with the master of platform.
As long as shopware 6 is in EA phase it is probably best to rely on master for development purposes as we still introduce breaking chances if we have to.

**Comment by almare** [comment]
Thank you for the clarification and merging.
