### ISSUE TITLE
BundleExample not working with variants

### ISSUE THREAD

**Issue by almare** [shopware/swag-docs-bundle-example#22]
I use the latest platform master branch and created a custom product with variants. It looks like that the variant with a bundle association is not fetched in the frontend. The extension array is empty even if the admin backend shows the correct bundle association for the variant.

**Comment by keulinho** [comment]
Hey @almare,
thanks for raising this issue.
The bundle association was not inheritance aware, which lead to this error.
We've fixed it in the linked PR, the docs will be updated accordingly.
