### ISSUE TITLE
The bundle-example is broken on current master

### ISSUE THREAD

**Issue by almare** [shopware/swag-docs-bundle-example#29]
After installing the bundle-example and visitng the listing I receive a 
`TypeError: "e is undefined"` 
message. The listing is completely broken.
If I try to add a new bundle and use the many-to-many dropdown I receve the same error.
Currently the bundle example is not usable.

**Comment by keulinho** [comment]
Fixed it with b7c393b444bf847a6490f8eb6856d99284698faa.
However the product many-to-many dropdown needs to be fixed in platform, that probably takes a day or two.

**Comment by almare** [comment]
Many thanks for the fast support :-)
