### ISSUE TITLE
Bundle Content not showing in OffCanvasMenu

### ISSUE THREAD

**Issue by DannyDan** [shopware/swag-docs-bundle-example#37]
When clicking on the "Bundle" entry in the OffCanvasMenu, the content is not shown. When clicking on "Description" or "Reviews" everything is working as excpected.

**Comment by DannyDan** [comment]
anyone who can reproduce this?

**Comment by simon-berger** [comment]
> anyone who can reproduce this?

I had this problem too.
You can fix this issue by change 'data-offcanvas-tab="true"' to 'data-offcanvas-tab**s**="true"'.
(The file you need to change is: swag-docs-bundle-example/src/Resources/views/storefront/page/product-detail/tabs.html.twig
)

**Comment by DannyDan** [comment]
@simon-berger 
WHAAAAT!?!?
I dont believe this! Its working now within my own tab.

Thank you very much!

@shopware
Did you actually test this example? Its really not helpful and it costs alot of extra time if the examples you provide are not working!

**Comment by mitelg** [comment]
thanks for the fix.

I updated the file :+1:
